const types = {
  TOGGLE_THEME: 'TOGGLE_THEME',
  TOGGLE_SEARCH_INPUT: 'TOGGLE_SEARCH_INPUT',
  TOGGLE_NAV_BAR: 'TOGGLE_NAV_BAR',
  ADD_TO_BASKET: 'ADD_TO_BASKET'
}
export const typesOfProducts = {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
}

export default types