const types = {
  TOGGLE_THEME: 'TOGGLE_THEME',
  TOGGLE_SEARCH_INPUT: 'TOGGLE_SEARCH_INPUT',
  TOGGLE_NAV_BAR: 'TOGGLE_NAV_BAR',
}
export const typesOfProducts = {
  GET_PRODUCT: 'GET_PRODUCT',
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS'
}

export const typesOfCategory = {
  GET_PORTABLE_POWER_STATION: 'GET_PORTABLE_POWER_STATION',
  GET_POWER_BANKS: 'GET_POWER_BANKS'
}

export default types